version: "3.9"
services:
  database:
    image: postgres:15.3
    container_name: studentregister
    ports:
      - "5441:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=student_register"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: